added decorator for sleep, added "create post" test
fishcka/QaComplexAppG6 pull request #3
Opened 2022-09-28 09:21 UTC by fishcka

це завдання на понеділок, довелось над ним посидіти тому не встигла зробити завдання на сьогодні.

складно було зрозуміти як правильно написати виділений рядок, у мене трохи не так вийшло як у тебе

```
class TestCreatePostPage:

    def test_create_post_page(self, login):
        # Navigate to create Post Page
        **header = login.navigate_to_create_post_page()**
        # Create Post
        header.create_post(title=random_symbols(15), body=random_symbols(150))
        # Verify the result
        header.verify_successfully_created()
```

2022-09-28 09:30 UTC, QALightLecorPython requested changes

2022-09-28 09:30 UTC, QALightLecorPython commented on pages/start_page.py
> +        return Header(self.driver)
It should returns new page, not element. 
In my project I'm calling it HelloPage

2022-09-28 09:30 UTC, QALightLecorPython commented on tests/test_create_post_page.py
> +        header = login.navigate_to_create_post_page()
Login page in fact doesn't have such functionality

2022-09-28 09:30 UTC, QALightLecorPython commented on tests/test_create_post_page.py
> +        header.create_post(title=random_symbols(15), body=random_symbols(150))
Seems it should be create_post_page instead of header

2022-10-03 01:54 UTC, fishcka commented
додала сторінку "hello_page.py", і переробила сторінку "test_create_post_page.py"
замість sign_up я логінюсь з зареєстрованим юзером, тому фікстура в пре-кондішені називається "login".

з декоратором логів погралась, але мої логи на кожну дію поки що подобаються мені більше.

з класами User i Post розібралась
клас User використала в тесті реєстрації і логіна з пустими параметрами

2022-10-03 15:15 UTC, QALightLecorPython approved these changes

2022-10-04 21:55 UTC, merged